import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { RequestContextProvider } from "../context/requestContext";
import { RecipeContextProvider } from "../context/recipeContext";
import { Providers } from "@/context/Providers";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body>
          <Providers>
            <Navbar />
            <RequestContextProvider>
              <RecipeContextProvider>{children}</RecipeContextProvider>
            </RequestContextProvider>
          </Providers>
        </body>
      </html>
    </>
  );
}
